apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
type: Opaque
data:
  docker-server: <base64-encoded-server>
  docker-username: <base64-encoded-username>
  docker-password: <base64-encoded-password>
  docker-email: <base64-encoded-email>
